apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: languagedepot

resources:
- deployment/base/config-map.yaml
- deployment/base/hg-deployment.yaml
- deployment/base/hasura-deployment.yaml
- deployment/base/lexbox-deployment.yaml
- deployment/base/proxy-deployment.yaml

configMapGenerator:
- name: otel-config
  files:
    - otel/collector-config.yaml
